trigger: none

parameters:
  - name: Image
    displayName: Pool Image
    default: macOS-latest
    type: string
    values:
      - windows-latest
      - ubuntu-latest
stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
         vmImage: ${{parameters.Image}}
     