trigger: none

parameters:
  - name: Image
    displayName: Pool Image
    default: macOS-latest
    type: string
    values:
      - windows-latest
      - ubuntu-latest
steps:
- script: echo Hello, world!
  displayName: 'Run-Time parameters are defined for pool'

